Camera + IMU
husarion/zed_cpu pull request #2
Opened 2023-05-30 08:45 UTC by rafal-gorecki

Wiele plików jest wykorzystanych z biblioteki [zed-open-capture](https://github.com/stereolabs/zed-open-capture) w związku z czym nie widze potrzeby ich sprawdzenia. Najbardziej zależałobymi na sprawdzeniu zed_cpu.cpp, CMakeList.txt, Readme.md

2023-05-30 10:26 UTC, KmakD requested changes

2023-05-30 10:26 UTC, KmakD commented on CMakeLists.txt
> +  image_transport
not alphabetical order

2023-05-30 10:26 UTC, KmakD commented on launch/zed.launch
> +<node pkg="zed_cpu" type="zed_node" name="zed_node"/>
```suggestion
  <node pkg="zed_cpu" type="zed_node" name="zed_node"/>
```

2023-05-30 10:26 UTC, KmakD commented on package.xml
> +<package format="2">
```suggestion
<package format="3">
```

2023-05-30 10:26 UTC, KmakD commented on package.xml
> +  <description>The zed_cpu package</description>
```suggestion
  <description>Package for ZED cameras running on CPU</description>
```

2023-05-30 10:26 UTC, KmakD commented on package.xml
> +  <maintainer email="support@husarion.com">Husarion</maintainer>
```suggestion
  <maintainer email="support@husarion.com">Husarion</maintainer>
  
  <url type="website">https://husarion.com/</url>
  <url type="repository">https://github.com/husarion/panther_ros</url>
  <url type="bugtracker">https://github.com/husarion/panther_ros/issues</url>
```

2023-05-30 10:26 UTC, KmakD commented on package.xml
> +  <depend>libusb-1.0-dev</depend>
not alphabetical order

2023-05-30 10:26 UTC, KmakD commented on README.md
> + * ROS
```suggestion
 * ROS Noetic
```

2023-05-30 10:26 UTC, KmakD commented on README.md
> +    `rosdep install --from-paths src --ignore-src -r -y`
```suggestion
* Install OpenCV to build the examples (optional):

    `sudo apt install libopencv-dev libopencv-viz-dev`

* Install ROS dependencies:

    `rosdep install --from-paths src --ignore-src -r -y`
```

2023-05-30 10:26 UTC, KmakD commented on README.md
> +    rosrun zed_cpu zed_node
since we have launch file we could use it + source ws after build:
```bash
source ~/ros_ws/devel/setup.bash
roslaunch zed_cpu zed.launch
```

2023-05-30 10:26 UTC, KmakD commented on README.md
> +    git clone https://github.com/husarion/zed-cpu.git src/zed-cpu
Cant write this as a suggestion but I would prefer putting command using \```:
\```bash
command
\```
Applies to all commands in this file

2023-05-30 10:26 UTC, KmakD commented on src/zed_cpu.cpp
This should be 3 separate files: main.cpp, zed_cpu_node.hpp zed_cpu_node.cpp
Also code does not match Husarion code style
For reference see eg. 
lights driver_node: https://github.com/husarion/panther_ros/blob/ros1/panther_lights/src/driver_node.cpp
joy2twist repo: https://github.com/husarion/joy2twist/tree/ros2/joy2twist

2023-05-30 15:01 UTC, KmakD requested changes
Includes does not match coding style. In headers you only include files that are used in that file. Also, you should always include files that are used in a file even if they were previously included in a header file.

2023-05-30 15:01 UTC, KmakD commented on include/zed_cpu/zed_cpu.hpp
> +  void publishIMU();
```suggestion
  void CameraInit();
  void SensorInit();
  void PublishImages();
  void PublishIMU();
```

2023-05-30 15:01 UTC, KmakD commented on include/zed_cpu/zed_cpu.hpp
> +  bool is_sensInit_;
```suggestion
  bool is_sens_init_;
```

2023-05-30 15:01 UTC, KmakD commented on src/zed_cpu.cpp
> +}
This could be a ros timer

2023-05-30 15:01 UTC, KmakD commented on src/main.cpp
> +  ZedCameraNode zedCameraNode(nh, it);
```suggestion
  ZedCameraNode zed_camera_node(nh, it);
```

2023-05-30 15:01 UTC, KmakD commented on src/main.cpp
> +  }
If you have timer instead of run method this can be changed to`ros::spin()`

2023-05-30 15:01 UTC, KmakD commented on src/main.cpp
> +  auto nh = std::make_shared<ros::NodeHandle>("~");
```suggestion
  auto nh = std::make_shared<ros::NodeHandle>();
```
I don't see a point in making this a private nh

2023-05-30 15:01 UTC, KmakD commented on src/zed_cpu.cpp
> +    ROS_ERROR("Cannot open camera video capture");
```suggestion
    ROS_ERROR("[%s] Cannot open camera video capture", node_name_.c_str());
```
node name you typically assign at the beginning of the constructor:
`node_name_ = ros::this_node::getName();`
Applies for all log messages

2023-05-30 15:01 UTC, KmakD commented on src/zed_cpu.cpp
> +  }
This should kill the node as there is no point for it to keep running

2023-05-30 15:01 UTC, KmakD commented on src/zed_cpu.cpp
> +  }
This should kill the node

2023-05-30 15:01 UTC, KmakD commented on src/zed_cpu.cpp
> +  sensorInit();
```suggestion
  sensorInit();
  
  ROS_INFO("[%s] Node started", node_name_.c_str());
```

2023-05-30 15:01 UTC, KmakD commented on src/zed_cpu.cpp
> +    cv::Mat frameBGR;
```suggestion
    cv::Mat frame_yuv = cv::Mat(frame.height, frame.width, CV_8UC2, frame.data);
    cv::Mat frame_bgr;
```

2023-05-30 15:01 UTC, KmakD commented on src/zed_cpu.cpp
> +    cv::Mat rightImage = frameBGR(cv::Rect(frameBGR.cols / 2, 0, frameBGR.cols / 2, frameBGR.rows));
```suggestion
    cv::Mat left_image = frameBGR(cv::Rect(0, 0, frameBGR.cols / 2, frameBGR.rows));
    cv::Mat right_image = frameBGR(cv::Rect(frameBGR.cols / 2, 0, frameBGR.cols / 2, frameBGR.rows));
```

2023-05-30 15:01 UTC, KmakD commented on src/zed_cpu.cpp
> +      cv_bridge::CvImage(std_msgs::Header(), "bgr8", rightImage).toImageMsg();
```suggestion
    sensor_msgs::ImagePtr left_msg =
      cv_bridge::CvImage(std_msgs::Header(), "bgr8", leftImage).toImageMsg();
    sensor_msgs::ImagePtr right_msg =
      cv_bridge::CvImage(std_msgs::Header(), "bgr8", rightImage).toImageMsg();
```

2023-05-30 15:01 UTC, KmakD commented on src/zed_cpu.cpp
> +  const sl_oc::sensors::data::Imu imuData = sens_->getLastIMUData(5000);
```suggestion
  const sl_oc::sensors::data::Imu imu_data = sens_->getLastIMUData(5000);
```

2023-05-30 15:01 UTC, KmakD commented on src/zed_cpu.cpp
> +    sensor_msgs::Imu imuMsg;
```suggestion
    sensor_msgs::Imu imu_msg;
```

2023-05-30 15:01 UTC, KmakD commented on README.md
> +    git clone https://github.com/husarion/zed-cpu.git src/zed-cpu
You forgot ```bash here

2023-05-30 15:01 UTC, KmakD commented on README.md
> +    `rosdep install --from-paths src --ignore-src -r -y`
Here you could also use ```bash

2023-05-31 09:02 UTC, rafal-gorecki commented on README.md
> +    git clone https://github.com/husarion/zed-cpu.git src/zed-cpu
done

2023-05-31 09:03 UTC, rafal-gorecki commented on package.xml
> +  <maintainer email="support@husarion.com">Husarion</maintainer>
done

2023-05-31 09:40 UTC, rafal-gorecki commented on src/zed_cpu.cpp
done

2023-05-31 10:09 UTC, rafal-gorecki commented on src/main.cpp
> +  auto nh = std::make_shared<ros::NodeHandle>("~");
Keeping similarity of topics to official zed-ros-wrapper

2023-05-31 10:20 UTC, rafal-gorecki commented on src/zed_cpu.cpp
> +}
I see no reason. Inside zed_lib there is checking if there is a new frame, and if not then the program goes to sleep. Adding rostimer will cased multiple sleeps (by zed_lib & ros timer), which should increase delay of receiving an image.

2023-05-31 10:25 UTC, rafal-gorecki commented on README.md
> +    `rosdep install --from-paths src --ignore-src -r -y`
For me there is no need to have 3 lines instead of one

2023-05-31 22:24 UTC, rafal-gorecki commented on src/zed_cpu.cpp
> +    RCLCPP_ERROR(nh_->get_logger(), "IMU initialize failed");
```suggestion
    ROS_ERROR("[%s] IMU initialize failed", node_name.c_str());
```

2023-05-31 22:31 UTC, rafal-gorecki commented on src/zed_cpu.cpp
> +    ROS_ERROR("[%s] IMU initialize failed", node_name.c_str());
```suggestion
    ROS_ERROR("[%s] IMU initialize failed", node_name_.c_str());
    ros::shutdown();
```

2023-06-01 10:06 UTC, KmakD commented on README.md
> +    `rosdep install --from-paths src --ignore-src -r -y`
Still I think it looks better when displaying, plus you can copy command using one click.

2023-06-01 10:45 UTC, KmakD requested changes

2023-06-01 10:45 UTC, KmakD commented on include/zed_cpu/zed_cpu.hpp
> +#include <image_transport/image_transport.h>
```suggestion
#include <memory>
#include <string>

#include <ros/ros.h>

#include <image_transport/image_transport.h>

#include "zed_lib/sensorcapture.hpp"
#include "zed_lib/videocapture.hpp"
```
Missing includes for standard library headers, custom project headers at the end, comments are unnecessary

2023-06-01 10:45 UTC, KmakD commented on src/zed_cpu.cpp
> +  std::cout<<node_name_<<std::endl;
```suggestion
```

2023-06-01 10:45 UTC, KmakD commented on src/zed_cpu.cpp
> +#include <opencv2/opencv.hpp>
```suggestion
#include <zed_cpu.hpp>

#include <memory>
#include <vector>

#include <cv_bridge/cv_bridge.h>
#include <ros/ros.h>
#include <opencv2/opencv.hpp>

#include <image_transport/image_transport.h>
#include <sensor_msgs/Imu.h>

#include "zed_lib/sensorcapture.hpp"
#include "zed_lib/videocapture.hpp"
```

2023-06-01 10:45 UTC, KmakD commented on include/zed_cpu/zed_cpu.hpp
Something I missed previously, `ZedCamerNode` should be inside `zed_cpu` namespace. Use same in cpp file
```
namespace zed_cpu
{
...
}  // namespace zed_cpu
```

2023-06-01 12:06 UTC, KmakD requested changes

2023-06-01 12:06 UTC, KmakD commented on src/main.cpp
> +  ZedCameraNode zed_camera_node(nh, it);
```suggestion
  zed_cpu::ZedCameraNode zed_camera_node(nh, it);
```
probably won't work without this.

2023-06-01 12:06 UTC, KmakD commented on src/zed_cpu.cpp
> +#include <sensor_msgs/Imu.h>
```suggestion
#include <ros/ros.h>

#include <sensor_msgs/Imu.h>
```

2023-06-02 11:12 UTC, KmakD approved these changes

2023-06-02 11:13 UTC, merged