ZED camra + imu for ROS2
husarion/zed_cpu pull request #3
Opened 2023-05-31 12:38 UTC by rafal-gorecki

Niewielkie zmiany w main.cpp, CMakeList i readme w stosunku do ROS1

2023-06-01 13:00 UTC, KmakD requested changes

2023-06-01 13:00 UTC, KmakD commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD_REQUIRED ON)
```suggestion
cmake_minimum_required(VERSION 3.10.2)
project(zed_cpu)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
Think we should go with c++17 for ROS2

2023-06-01 13:00 UTC, KmakD commented on include/zed_cpu/zed_cpu.hpp
> +class ZedCameraNode
```suggestion
namespace zed_cpu
{

class ZedCameraNode : public rclcpp::Node
```
For ROS 2 this approach is more common

2023-06-01 13:00 UTC, KmakD commented on include/zed_cpu/zed_cpu.hpp
> +    const std::shared_ptr<image_transport::ImageTransport> & it);
```suggestion
  ZedCameraNode(const std::shared_ptr<image_transport::ImageTransport> & it);
```

2023-06-01 13:00 UTC, KmakD commented on package.xml
> +  <depend>rclcpp</depend>
```suggestion
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
```

2023-06-01 13:00 UTC, KmakD commented on package.xml
> +  <url type="bugtracker">https://github.com/husarion/zed_cpu/issues</url>
```suggestion
  <maintainer email="support@husarion.com">Husarion</maintainer>

  <url type="website">https://husarion.com/</url>
  <url type="repository">https://github.com/husarion/zed_cpu</url>
  <url type="bugtracker">https://github.com/husarion/zed_cpu/issues</url>
```

2023-06-01 13:00 UTC, KmakD commented on src/main.cpp
> +  }
```suggestion
  auto it = std::make_shared<image_transport::ImageTransport>(node);
  auto zed_camera_node = std::make_shared<zed_cpu::ZedCameraNode>(it);

  while (rclcpp::ok()) {
    zed_camera_node.run();
    rclcpp::spin_some(zed_camera_node);
  }
```

2023-06-01 13:00 UTC, KmakD commented on src/zed_cpu.cpp
> +: nh_(nh), it_(it)
```suggestion
ZedCameraNode::ZedCameraNode(const std::shared_ptr<image_transport::ImageTransport> & it)
: Node("zed_camera_node"), it_(it)
```

2023-06-01 13:00 UTC, KmakD commented on src/zed_cpu.cpp
> +  imu_pub_ = nh_->create_publisher<sensor_msgs::msg::Imu>("imu_data", 1);
```suggestion
  imu_pub_ = this->create_publisher<sensor_msgs::msg::Imu>("imu_data", 1);
```

2023-06-01 13:00 UTC, KmakD commented on src/zed_cpu.cpp
> +  SensorInit();
```suggestion
  SensorInit();
  
  RCLCPP_INFO(get_logger(), "Node started");
```

2023-06-01 13:00 UTC, KmakD commented on src/zed_cpu.cpp
> +    RCLCPP_ERROR(nh_->get_logger(), "Cannot open camera video capture");
```suggestion
    RCLCPP_ERROR(get_logger(), "Cannot open camera video capture");
```
same for all logs

2023-06-01 13:00 UTC, KmakD commented on src/zed_cpu.cpp
> +    imu_msg.header.stamp = nh_->get_clock()->now();
```suggestion
    imu_msg.header.stamp = get_clock()->now();
```

2023-06-01 13:00 UTC, KmakD commented on README.md
> +    git clone https://github.com/husarion/zed-cpu.git src/zed-cpu
add ```bash

2023-06-01 13:00 UTC, KmakD commented on README.md
> +    `rosdep install --from-paths src --ignore-src -r -y`
add ``` bash

2023-06-01 18:44 UTC, rafal-gorecki commented on README.md
> +    git clone https://github.com/husarion/zed-cpu.git src/zed-cpu
```suggestion
```bash
mkdir -p ros_ws/src
cd ros_ws
git clone https://github.com/husarion/zed-cpu.git src/zed-cpu
```
```

2023-06-02 08:27 UTC, KmakD requested changes

2023-06-02 08:27 UTC, KmakD commented on src/zed_cpu.cpp
> +  RCLCPP_INFO(get_logger(), "Node started");
```suggestion
  imu_pub_ = this->create_publisher<sensor_msgs::msg::Imu>("imu_data", 1);

  CameraInit();
  SensorInit();

  RCLCPP_INFO(this->get_logger(), "Node started");
```
It is generally advised to include "this"  when calling member functions of current instance. It improves code clarity, and helps avoiding ambiguity (eg. class having function with the same name). Sorry for confusion with `get_logger`.

2023-06-02 08:27 UTC, KmakD commented on src/zed_cpu.cpp
> +    imu_msg.header.stamp = get_clock()->now();
```suggestion
    imu_msg.header.stamp = this->get_clock()->now();
```

2023-06-02 08:27 UTC, KmakD commented on src/zed_cpu.cpp
> +ZedCameraNode::ZedCameraNode() : Node("zed_camera", "zed_camera")
I'm wondering if it wouldn't be a better idea to add namespace in launch file, with launch argument with default value "zed_camera". Better for multiple cameras implementations.

2023-06-02 08:27 UTC, KmakD commented on include/zed_cpu/zed_cpu.hpp
> +  image_transport::Publisher right_image_pub_;
I think this should be unique_ptr. Alternatively, you can create ImageTransport shared_ptr object something like:
```
# zed_cpu.hpp
std::shared_ptr<image_transport::ImageTransport> it_;

# zed_cpu.cpp (constructor)
it_ = std::make_shared<image_transport::ImageTransport>(shared_from_this());
```

2023-06-02 09:35 UTC, rafal-gorecki commented on src/zed_cpu.cpp
> +ZedCameraNode::ZedCameraNode() : Node("zed_camera", "zed_camera")
User still can use `namespace` argumet to override this

2023-06-02 09:59 UTC, rafal-gorecki commented on include/zed_cpu/zed_cpu.hpp
> +  image_transport::Publisher right_image_pub_;
I tried this and it caused error: terminate called after throwing an instance of 'std::bad_weak_ptr' in this line:
`it_ = std::make_shared<image_transport::ImageTransport>(shared_from_this());`

In other hand using unique_ptr comes down to using the following command:
`left_image_pub_ = std::make_unique<image_transport::Publisher>(rclcpp::Node*, const string&, image_transport::PubLoaderPtr, rmw_qos_profile_t);`

2023-06-02 11:58 UTC, merged